### ISSUE TITLE
Out of Memory exception

### ISSUE THREAD

**Issue by RyudoGaming** [esperknight/CriPakTools#6]
Hi ive been trying to Extract all from a Data.CPK but it extracts a few of the files then gives a Unhandled Exception: OutOfMemoryException. i have tried a few different versions Master, GUI etc and each one gives the error

Im running windows 10 with 16 gigs of Ram
i gave at least 40gigs left and the data.cpk is 2gigs, 
even extracted it wouldn't come to above 40.

if it helps the game i am trying to extract is .Hack//Versus 
you can see my thread on it here [http://forum.xentax.com/viewtopic.php?f=10&t=18099](url)

**Comment by esperknight** [comment]
Looking at your issue.  It may be something I fixed a while back and forgot to commit/upload.  I did that just now so you'll find a new version under the Build folder (or just click on this https://github.com/esperknight/CriPakTools/blob/master/Build/CriPakTools.exe).

For your screenshot, I'm honestly not sure as i don't use the CpkMaker tool very much preferring my own instead.

If this doesn't fix it let me know though.  If you could also upload the CPK somewhere as that'll make it easier.

**Comment by RyudoGaming** [comment]
Whilst i upload the file as its about 2 gigs just to make sure i am using the correct input its:

CriPakTools Data.cpk data\ui\attention\JP\attention.xfbin data\ui\attention\JP\attention.xfbin

Data.cpk being the og CPK file
first data\ui etc being the location in the data archive
second data etc being the file to replace it with?

**Comment by esperknight** [comment]
Ack, yeah... Forgot to push them.  Should be up to date now.  Only change is to remove grabbing the timestamps.  Can't recall why that was originally done so I took it out.

**Comment by Fallenleader** [comment]
I am having a similar issue with Hollow Realization. Extract all gets to this point and returns this error. I snipped out up to the file before the one giving the error for simplicity sake:

`Extracting: effb/sds_debug.bin
Extracting: effect/000.pak

Unhandled Exception: System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.MemoryStream.InternalReadInt32()
   at CriPakTools.EndianReader.ReadInt32()
   at CriPakTools.CPK.DecompressCRILAYLA(Byte[] input, Int32 USize)
   at CriPakTools.Program.Main(String[] args)`

As you can see here, it hangs on 000.pak. I am using the latest binary.
